const corrections = [
  ["Mechanic engineering", "Mechanical engineering"],
  ["Electrical enginieering", "Electrical engineering"],
  ["Ingeneering", "Engineering"],
  ["civil enginieering", "Civil engineering"],
  ["Compuer science", "Computer science"],
  ["Urban planes", "Urban planning"],
  ["Harticulture", "Horticulture"],
  ["hostpitality", "Hospitality"],
  ["Marketting", "Marketing"],
  ["Manufaturing", "Manufacturing"],
  ["Bankimg and finacial servises", "Banking and financial services"],
  ["Construcion", "Construction"],
  ["Educatuon", "Education"],
  ["Reterail, Reatil, Reetail", "Retail"],
  ["Transportaion", "Transportation"],
  ["Enviromental planning", "Environmental planning"],
  ["phinance and banking", "Finance and banking"],
  ["Health care", "Health care"],
  ["Aerspace engineering", "Aerospace engineering"],
  ["Matierals science", "Materials science"],
  ["industrial engineer", "Industrial engineering"],
  ["Material science", "Materials science"],
  ["industrail engineering", "Industrial engineering"],
  ["Nusring", "Nursing"],
  ["Veterinary nurcing", "Veterinary nursing"],
  ["Aged caree", "Aged care"],
  ["Childred education", "Childhood education"],
  ["Dental nurcing", "Dental nursing"],
  ["Podiatry nursing", "Podiatric nursing"],
  ["Nurseaide", "Nurse aide"],
  ["Interpeter", "Interpreter"],
  ["Dental nusing", "Dental nursing"],
  ["Podiatry nursing", "Podiatric nursing"],
  ["Sport nursing", "Sports nursing"],
  ["adult aducation", "Adult education"],
  ["Carreer education", "Career education"],
  ["Krytical thinking", "Critical thinking"],
  ["Design thinkng", "Design thinking"],
  ["Social worry", "Social work"],
  ["Beekeping", "Beekeeping"],
  ["looksmithing", "Locksmithing"],
];

module.exports = corrections;